# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0e8264e809c48ce91590616b93d66f8a62be38b987a2da80d5f794bfbe945a3b82caa6d81e39aa978c530578ecd4dde85f3d12460de12bbed98dc85ed572fb8

test:
  secret_key_base: 7268c381763a06e759be95c7a7670fcbc21e3eb4f178ba310962919a993844d30b5fcba7b0807385a43f34ba1c71412c3a223975b9fd728cb7c97bdf84140188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
